version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "2613:2612"
     - "80:1234"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

